<template>
  <div class="loadingio-spinner-eclipse-njmexhjkc7c">
    <div class="ldio-mco7ywbd4w">
      <div></div>
    </div>
  </div>
</template>
<script setup></script>

<style scoped>
@keyframes ldio-mco7ywbd4w {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(180deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-mco7ywbd4w div {
  position: absolute;
  animation: ldio-mco7ywbd4w 1s linear infinite;
  width: 84.39999999999999px;
  height: 84.39999999999999px;
  top: 63.3px;
  left: 63.3px;
  border-radius: 50%;
  box-shadow: 0 2.11px 0 0 #e15b64;
  transform-origin: 42.199999999999996px 43.254999999999995px;
}
.loadingio-spinner-eclipse-njmexhjkc7c {
  width: 211px;
  height: 211px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-mco7ywbd4w {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-mco7ywbd4w div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
